services:
  db:
    image: postgres:15-alpine
    container_name: exptrack-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - exptrack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./exptrack-backend
      dockerfile: dockerfile
    container_name: exptrack-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      SSL_KSP12: ${SSL_KSP12}
      SSL_KSPW: ${SSL_KSPW}
      SERVER_SSL_KEY_ALIAS: localhost
    ports:
      - "8443:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - exptrack-network

volumes:
  postgres_data:

networks:
  exptrack-network:
    driver: bridge
